# Generated by Django 4.2.17 on 2025-01-12 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="plantsitter",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who accepted the task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="requester",
            field=models.ForeignKey(
                help_text="The user who created the task",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_posted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
